services:
  mariadb:
    build: ./requirements/mariadb
    tty: true
    stdin_open: true
    ports:
      - "3306:3306"
  nginx:
    build: ./requirements/nginx
    tty: true
    stdin_open: true
    ports:
      - "443:443"

#other stuff below
