services:
  mariadb:
    build: ./requirements/mariadb
    tty: true
    stdin_open: true
    command: /bin/sh
    ports:
      - "3306:3306"
    secrets:
      - db_password
      - db_root_password

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt

#other stuff below
